In [3]:
import torch

x = torch.ones(2,2, requires_grad=True)

x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
y = (x  + 2) * (x+5)

In [5]:
y

tensor([[18., 18.],
        [18., 18.]], grad_fn=<MulBackward0>)

In [6]:
y.grad

In [8]:
z = y.mean()

In [10]:
z

tensor(18., grad_fn=<MeanBackward0>)

In [9]:
z.backward()

In [11]:
z

tensor(18., grad_fn=<MeanBackward0>)

# Exercise 1

In [32]:
x = torch.randn(2,2)
print(x)
print(x.shape)

tensor([[-1.3289,  0.0696],
        [-1.4795,  3.8869]])
torch.Size([2, 2])


In [33]:
x.unsqueeze_(0)
print(x)
x.shape

tensor([[[-1.3289,  0.0696],
         [-1.4795,  3.8869]]])


torch.Size([1, 2, 2])

# Exercise: 2

In [34]:
x.squeeze_(0)
print(x)
x.shape

tensor([[-1.3289,  0.0696],
        [-1.4795,  3.8869]])


torch.Size([2, 2])

# Exercise: 3

In [37]:
torch.randint(3, 8, (5, 3))

tensor([[5, 6, 6],
        [7, 6, 4],
        [6, 6, 5],
        [3, 7, 7],
        [7, 7, 3]])

In [40]:
torch.Tensor(5, 3).uniform_(3, 8)

tensor([[5.1243, 5.7978, 4.3882],
        [3.4439, 3.4249, 7.2363],
        [7.6273, 5.4540, 5.0045],
        [3.3700, 6.1493, 3.9137],
        [3.3918, 7.9251, 6.4696]])

# Exercise: 4

In [49]:
x = torch.Tensor(10, 5)

x.normal_(mean=0, std=1) #mean 0 and std=1

tensor([[ 0.7784,  0.2667,  0.7935,  1.9736, -0.6327],
        [-2.4924,  0.6358,  1.0391, -0.7198,  0.9486],
        [ 0.1138,  0.3129, -0.3111,  0.0648, -0.3483],
        [ 1.2208, -0.7782,  1.0855,  0.8670,  0.3286],
        [-1.1222,  0.0601,  0.3316,  1.2419, -0.3176],
        [-1.0667,  0.6064,  1.0086, -0.8000,  0.8791],
        [-0.9895,  1.3998,  0.1910,  0.7361,  1.3052],
        [ 1.3701,  0.6423,  0.8081,  0.3887,  1.1566],
        [-0.3152,  0.1587, -1.0851,  0.4903,  0.1593],
        [-0.9335, -1.3974, -2.9171,  0.3361,  1.4202]])

# Exercise: 5

In [61]:
x = torch.Tensor([1, 1, 1, 0, 1])
torch.nonzero(x).view(-1)

tensor([0, 1, 2, 4])

# Exercise: 6

In [85]:
x = torch.Tensor(3, 1)

In [87]:
x = x.expand(3, 4)
x

tensor([[2.5226e-18, 2.5226e-18, 2.5226e-18, 2.5226e-18],
        [1.6898e-04, 1.6898e-04, 1.6898e-04, 1.6898e-04],
        [1.0527e-11, 1.0527e-11, 1.0527e-11, 1.0527e-11]])

In [89]:
x = torch.Tensor(3, 1)
y = torch.Tensor(3, 4)
x.expand_as(y)

tensor([[-1.3266e-10, -1.3266e-10, -1.3266e-10, -1.3266e-10],
        [ 3.0789e-41,  3.0789e-41,  3.0789e-41,  3.0789e-41],
        [-1.5370e-10, -1.5370e-10, -1.5370e-10, -1.5370e-10]])

# Exercise: 7

In [90]:
x = torch.rand(3,4,5)
y = torch.rand(3,5,4)
torch.bmm(x, y)

tensor([[[0.8481, 1.1031, 0.9539, 1.1527],
         [0.5319, 0.4473, 0.3699, 0.4971],
         [1.6326, 1.5202, 1.4203, 1.5472],
         [1.3562, 1.1865, 0.8529, 1.3167]],

        [[0.6579, 1.3257, 0.9248, 1.0498],
         [1.1434, 1.6675, 0.9907, 1.4457],
         [0.5344, 1.1817, 0.6995, 0.8913],
         [0.9857, 2.1115, 1.4314, 1.4365]],

        [[1.7892, 1.6843, 1.3642, 2.5696],
         [1.3544, 1.3804, 1.3123, 2.1169],
         [1.3762, 0.9285, 0.7865, 1.5726],
         [1.3827, 1.2161, 0.7844, 1.8726]]])

# Exercise: 8

In [132]:
x = torch.rand(3,4,5)
y = torch.rand(5,4)

In [133]:
x

tensor([[[0.5413, 0.0129, 0.3002, 0.7015, 0.4328],
         [0.2465, 0.8919, 0.7661, 0.7208, 0.6462],
         [0.5218, 0.3262, 0.3897, 0.4318, 0.7376],
         [0.6305, 0.3516, 0.6883, 0.5035, 0.7270]],

        [[0.8896, 0.9755, 0.6796, 0.0707, 0.3400],
         [0.0699, 0.0188, 0.1514, 0.3427, 0.5004],
         [0.8054, 0.1139, 0.5378, 0.6899, 0.4956],
         [0.6933, 0.0038, 0.9476, 0.8401, 0.1806]],

        [[0.6816, 0.3605, 0.3528, 0.0246, 0.5015],
         [0.5215, 0.7860, 0.9462, 0.6302, 0.4671],
         [0.7337, 0.2485, 0.7982, 0.3566, 0.0075],
         [0.0137, 0.1546, 0.1029, 0.0840, 0.8884]]])

In [135]:
y2 = torch.Tensor(3, 5, 4)
y = y.expand_as(y2)
y

tensor([[[0.5414, 0.0551, 0.3057, 0.1609],
         [0.0192, 0.4428, 0.6564, 0.5359],
         [0.6694, 0.3144, 0.8834, 0.1748],
         [0.0656, 0.0126, 0.3808, 0.1750],
         [0.9869, 0.8175, 0.5100, 0.7709]],

        [[0.5414, 0.0551, 0.3057, 0.1609],
         [0.0192, 0.4428, 0.6564, 0.5359],
         [0.6694, 0.3144, 0.8834, 0.1748],
         [0.0656, 0.0126, 0.3808, 0.1750],
         [0.9869, 0.8175, 0.5100, 0.7709]],

        [[0.5414, 0.0551, 0.3057, 0.1609],
         [0.0192, 0.4428, 0.6564, 0.5359],
         [0.6694, 0.3144, 0.8834, 0.1748],
         [0.0656, 0.0126, 0.3808, 0.1750],
         [0.9869, 0.8175, 0.5100, 0.7709]]])

In [136]:
torch.bmm(x, y)

tensor([[[0.9674, 0.4926, 0.9270, 0.6029],
         [1.3484, 1.1867, 1.9417, 1.2759],
         [1.3058, 0.9041, 1.2584, 0.9710],
         [1.5593, 1.0075, 1.5941, 1.0587]],

        [[1.2954, 0.9734, 1.7130, 1.0592],
         [0.6558, 0.4732, 0.5531, 0.4935],
         [1.3327, 0.6778, 1.3116, 0.7875],
         [1.2430, 0.4960, 1.4636, 0.5654]],

        [[1.1087, 0.7185, 1.0219, 0.7555],
         [1.4331, 1.0640, 1.9895, 1.1409],
         [0.9671, 0.4120, 1.2322, 0.4589],
         [0.9615, 0.8289, 0.6816, 0.8026]]])

In [137]:
a = torch.rand(3,4,5)
b = torch.rand(5,4)
torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size()))

tensor([[[0.1934, 0.5644, 0.6113, 0.3344],
         [1.0347, 1.3323, 1.6011, 1.3337],
         [0.8783, 0.9418, 1.0668, 1.0417],
         [0.8900, 1.0076, 1.1627, 1.1287]],

        [[1.0577, 1.3016, 1.2412, 1.3507],
         [0.6521, 1.0333, 0.8437, 0.8873],
         [0.9052, 1.5109, 1.4642, 1.2370],
         [1.0921, 1.4228, 1.7841, 1.3520]],

        [[0.5348, 1.3154, 0.9643, 0.9494],
         [1.2301, 1.8103, 1.6966, 1.6391],
         [1.0295, 1.1246, 1.0754, 1.2145],
         [1.0552, 1.2537, 1.4872, 1.2681]]])